### ISSUE TITLE
[Small Contributions] Notify contributors about reached limit(s)

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack/management#3]
Adding an upper limit for 'smaller contributions' is a a good idea, but since there is no public tracking about ones contribution status it is difficult to manage your time and resources spend on contributing to `webpack/webpack-contrib`. Contributors should therefore be at least notified if the their (monthly) limit for payed contributions is reached and that further contributions won't be payed (with the intend to devote your time to something else instead). This encourages to manage ones workload/time within a range that is substainable for the individual and the project itself. A notification handles the substainable part on the individual side of affairs

**Comment by sokra** [comment]
Sounds good. Currently this is difficult for technical reasons, but I look into options to provide this.
